package br.unioeste.jgoose.view;

import br.unioeste.jgoose.controller.BPMNController;
import br.unioeste.jgoose.controller.Controller;
import br.unioeste.jgoose.controller.EditorWindowListener;
import br.unioeste.jgoose.controller.ImportBPMNGraph;
import br.unioeste.jgoose.controller.ImportIStarGraph;
import br.unioeste.jgoose.controller.HorizontalBPMNTraceController;
import br.unioeste.jgoose.controller.HorizontalIStarTraceController;
import br.unioeste.jgoose.controller.HorizontalUseCaseTraceController;
import br.unioeste.jgoose.controller.VerticalTraceController;
import br.unioeste.jgoose.e4j.swing.BasicBPMNEditor;
import br.unioeste.jgoose.e4j.swing.BasicIStarEditor;
import br.unioeste.jgoose.e4j.swing.BasicUseCasesEditor;
import br.unioeste.jgoose.e4j.swing.EditorJFrame;
import br.unioeste.jgoose.e4j.swing.menubar.EditorMenuBar;
import br.unioeste.jgoose.model.BPMNLink;
import br.unioeste.jgoose.model.IStarElement;
import br.unioeste.jgoose.model.IStarLink;
import com.mxgraph.util.mxResources;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import org.apache.log4j.Logger;

/**
 *
 * @authors 
 * @Diego Peliser
 * @Alysson Girotto
 * @Victor Augusto Pozzan
 */
public class MainView extends javax.swing.JFrame {

    private UseCasesView useCasesView = null;
    private TableArtifacts tableArtifacts = null;
    private UseCasesViewBPMN useCasesViewBPMN = null;
    private static final Logger LOG = Logger.getLogger("console");
    private EditorJFrame E4JiStar = null;
    private EditorJFrame E4JUseCases = null;
    private EditorJFrame E4JBPMN = null;
    private JFrame E4JTraceability = null;
    private BasicBPMNEditor editor;
    
    private Image iconJGOOSE = Toolkit.getDefaultToolkit().getImage("./src/main/resources/icons/jgoose.gif");
    Font roboto;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();                        
        setLocationRelativeTo(null);
        setIconImage(iconJGOOSE);
        //Set the theme of swing equals to SO.
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            LOG.error("LookAndFeel Error!", e);
        }
        
        setDefaultLookAndFeelDecorated(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(true);
        //dispose();
        //setVisible(true);
       
        try{
            InputStream myStream = new BufferedInputStream(new FileInputStream("./src/main/resources/fonts/Roboto-Black.ttf"))  ;
            roboto = Font.createFont(Font.TRUETYPE_FONT, myStream);
            roboto = roboto.deriveFont(30f);
            
        }catch(IOException | FontFormatException e){
            System.out.println(e);
        }
        menuBar.setOpaque(true);
        menuBar.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(new java.awt.Color(11, 113, 165));
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }         
    });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form BasicIStarEditor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonOpenE4JBPMN = new javax.swing.JButton();
        buttonOpenE4JiStar = new javax.swing.JButton();
        buttonOpenE4JUseCases = new javax.swing.JButton();
        buttunMappingUseCases = new javax.swing.JButton();
        buttonOpenTelosFile = new javax.swing.JButton();
        buttonBPMNToUseCases = new javax.swing.JButton();
        btnTraceability = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileOpenTelosFile = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        toolsOpenE4JBPMNEditor = new javax.swing.JMenuItem();
        toolsOpenE4JEditor = new javax.swing.JMenuItem();
        toolsOpenE4JUCEditor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        helpGuidelines = new javax.swing.JMenuItem();
        helpAbout = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMaximumSize(null);
        setName("home"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 0));

        buttonOpenE4JBPMN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonOpenE4JBPMN.setText("E4J BPMN");
        buttonOpenE4JBPMN.setToolTipText("Abrir Editor BPMN");
        buttonOpenE4JBPMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenE4JBPMNActionPerformed(evt);
            }
        });

        buttonOpenE4JiStar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonOpenE4JiStar.setText("E4J i*");
        buttonOpenE4JiStar.setToolTipText("Abrir Arquivo Telos");
        buttonOpenE4JiStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenE4JiStarActionPerformed(evt);
            }
        });

        buttonOpenE4JUseCases.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonOpenE4JUseCases.setText("E4J Use Cases");
        buttonOpenE4JUseCases.setToolTipText("Abrir Arquivo Telos");
        buttonOpenE4JUseCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenE4JUseCasesActionPerformed(evt);
            }
        });

        buttunMappingUseCases.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttunMappingUseCases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usecases_32x32.png"))); // NOI18N
        buttunMappingUseCases.setText("Mapping Use Cases UML");
        buttunMappingUseCases.setToolTipText("Mapear Casos de Uso UML");
        buttunMappingUseCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttunMappingUseCasesActionPerformed(evt);
            }
        });

        buttonOpenTelosFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonOpenTelosFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_open_32x32.png"))); // NOI18N
        buttonOpenTelosFile.setText("Open Telos File");
        buttonOpenTelosFile.setToolTipText("Abrir Arquivo Telos");
        buttonOpenTelosFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenTelosFileActionPerformed(evt);
            }
        });

        buttonBPMNToUseCases.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonBPMNToUseCases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/toUC_32x32.png"))); // NOI18N
        buttonBPMNToUseCases.setText("Mapping BPMN to Use Cases");
        buttonBPMNToUseCases.setToolTipText("Derivar Casos de Uso a partir de BPMN");
        buttonBPMNToUseCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBPMNToUseCasesActionPerformed(evt);
            }
        });

        btnTraceability.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTraceability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/traceability_32x32.png"))); // NOI18N
        btnTraceability.setText("Traceability");
        btnTraceability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraceabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(buttonOpenE4JBPMN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buttonOpenE4JiStar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buttonOpenE4JUseCases, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buttunMappingUseCases, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buttonOpenTelosFile, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buttonBPMNToUseCases, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnTraceability, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpenE4JBPMN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpenE4JiStar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpenE4JUseCases, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttunMappingUseCases, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpenTelosFile, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBPMNToUseCases, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTraceability, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 69, 101));
        jLabel1.setText("JGOOSE");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 63, 75));
        jLabel2.setText("helping software engeneerings");

        menuBar.setBackground(new java.awt.Color(255, 102, 0));
        menuBar.setForeground(new java.awt.Color(153, 0, 102));
        menuBar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        menuBar.setMaximumSize(new java.awt.Dimension(154, 50));
        menuBar.setMinimumSize(new java.awt.Dimension(154, 25));
        menuBar.setName(""); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(154, 50));
        menuBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuBarFocusGained(evt);
            }
        });

        menuFile.setBackground(new java.awt.Color(11, 113, 165));
        menuFile.setForeground(new java.awt.Color(254, 254, 254));
        menuFile.setText("Files");
        menuFile.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        menuFile.setMargin(new java.awt.Insets(0, 20, 0, 20));
        menuFile.setOpaque(true);

        fileOpenTelosFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        fileOpenTelosFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_open_16x16.png"))); // NOI18N
        fileOpenTelosFile.setText("Open Telos File");
        fileOpenTelosFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenTelosFileActionPerformed(evt);
            }
        });
        menuFile.add(fileOpenTelosFile);

        menuBar.add(menuFile);

        menuTools.setBackground(new java.awt.Color(11, 113, 165));
        menuTools.setForeground(new java.awt.Color(254, 254, 254));
        menuTools.setText("Tools");
        menuTools.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        menuTools.setMargin(new java.awt.Insets(0, 20, 0, 20));
        menuTools.setOpaque(true);

        toolsOpenE4JBPMNEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        toolsOpenE4JBPMNEditor.setText("E4J BPMN");
        toolsOpenE4JBPMNEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsOpenE4JBPMNEditorActionPerformed(evt);
            }
        });
        menuTools.add(toolsOpenE4JBPMNEditor);

        toolsOpenE4JEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        toolsOpenE4JEditor.setText("E4J i*");
        toolsOpenE4JEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsOpenE4JEditorActionPerformed(evt);
            }
        });
        menuTools.add(toolsOpenE4JEditor);

        toolsOpenE4JUCEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        toolsOpenE4JUCEditor.setText("E4J Use Cases");
        toolsOpenE4JUCEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsOpenE4JUCEditorActionPerformed(evt);
            }
        });
        menuTools.add(toolsOpenE4JUCEditor);

        jMenuItem1.setText("Tabelas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem1);

        menuBar.add(menuTools);

        menuHelp.setBackground(new java.awt.Color(11, 113, 165));
        menuHelp.setForeground(new java.awt.Color(254, 254, 254));
        menuHelp.setText("Help");
        menuHelp.setFocusTraversalPolicyProvider(true);
        menuHelp.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        menuHelp.setMargin(new java.awt.Insets(0, 20, 0, 20));
        menuHelp.setOpaque(true);

        helpGuidelines.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpGuidelines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guidelines_16x16.png"))); // NOI18N
        helpGuidelines.setText("Guidelines");
        helpGuidelines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpGuidelinesActionPerformed(evt);
            }
        });
        menuHelp.add(helpGuidelines);

        helpAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        helpAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_16x16.png"))); // NOI18N
        helpAbout.setText("About");
        helpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpAboutActionPerformed(evt);
            }
        });
        menuHelp.add(helpAbout);

        menuBar.add(menuHelp);

        about.setBackground(new java.awt.Color(11, 113, 165));
        about.setForeground(new java.awt.Color(254, 254, 254));
        about.setText("About");
        about.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        about.setMargin(new java.awt.Insets(0, 20, 0, 20));
        about.setOpaque(true);
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
        });
        menuBar.add(about);

        jMenu1.setBackground(new java.awt.Color(11, 113, 165));
        jMenu1.setForeground(new java.awt.Color(254, 254, 254));
        jMenu1.setText("Les");
        jMenu1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jMenu1.setOpaque(true);
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraceabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraceabilityActionPerformed
        try {
            this.showTraceability();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTraceabilityActionPerformed

    private void buttonBPMNToUseCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBPMNToUseCasesActionPerformed
        BPMNController.mapUseCases();
        if (useCasesViewBPMN == null) {
            useCasesViewBPMN = new UseCasesViewBPMN();
            useCasesViewBPMN.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        }
        useCasesViewBPMN.updateTable();
        useCasesViewBPMN.setVisible(true);
    }//GEN-LAST:event_buttonBPMNToUseCasesActionPerformed

    private void buttonOpenTelosFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenTelosFileActionPerformed
        Controller.setMainView(this);
        Controller.openTelosFile();
    }//GEN-LAST:event_buttonOpenTelosFileActionPerformed

    private void buttunMappingUseCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttunMappingUseCasesActionPerformed
        Controller.mapUseCases();
        if (useCasesView == null) {
            useCasesView = new UseCasesView();
            useCasesView.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        }
        useCasesView.updateTabel();
        useCasesView.setVisible(true);
    }//GEN-LAST:event_buttunMappingUseCasesActionPerformed

    private void buttonOpenE4JUseCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenE4JUseCasesActionPerformed
        try {
            this.showE4JUseCases();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonOpenE4JUseCasesActionPerformed

    private void buttonOpenE4JiStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenE4JiStarActionPerformed
        try {
            this.showE4JiStar();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonOpenE4JiStarActionPerformed

    private void buttonOpenE4JBPMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenE4JBPMNActionPerformed
        try {
            this.showE4JBPMN();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonOpenE4JBPMNActionPerformed

    private void menuBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuBarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarFocusGained

    private void helpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpAboutActionPerformed
        this.showAboutDialog();
    }//GEN-LAST:event_helpAboutActionPerformed

    private void helpGuidelinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpGuidelinesActionPerformed
        this.showGuidelinesDialog();
    }//GEN-LAST:event_helpGuidelinesActionPerformed

    private void toolsOpenE4JUCEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsOpenE4JUCEditorActionPerformed
        try {
            this.showE4JUseCases();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toolsOpenE4JUCEditorActionPerformed

    private void toolsOpenE4JEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsOpenE4JEditorActionPerformed
        try {
            this.showE4JiStar();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toolsOpenE4JEditorActionPerformed

    private void toolsOpenE4JBPMNEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsOpenE4JBPMNEditorActionPerformed
        try {
            this.showE4JBPMN();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toolsOpenE4JBPMNEditorActionPerformed

    private void fileOpenTelosFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenTelosFileActionPerformed
        Controller.openTelosFile();
    }//GEN-LAST:event_fileOpenTelosFileActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            this.showArtfactTables();
        } catch (HeadlessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
           
        about.setBackground(Color.GREEN);
    }//GEN-LAST:event_aboutMouseEntered

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
         about.setBackground(Color.BLACK);
    }//GEN-LAST:event_aboutMouseExited

    /**
     * Abre uma janela GuidelinesDialogView
     */
    private void showGuidelinesDialog() {
        GuidelinesDialogView diretrizes;
        try {
            diretrizes = new GuidelinesDialogView(this);
            diretrizes.setModal(true);
            int x = this.getX() + (this.getWidth() - diretrizes.getWidth()) / 2;
            int y = this.getY() + (this.getHeight() - diretrizes.getHeight()) / 2;
            diretrizes.setLocation(x, y);
            diretrizes.setVisible(true);
        } catch (BadLocationException ex) {
            LOG.error(ex);
        }
    }

    /**
     * Abre uma janela AboutDialogView
     */
    private void showAboutDialog() {
        AboutDialogView about;
        about = new AboutDialogView(this);
        about.setModal(true);
        int x = this.getX() + (this.getWidth() - about.getWidth()) / 2;
        int y = this.getY() + (this.getHeight() - about.getHeight()) / 2;
        about.setLocation(x, y);
        about.setVisible(true);
    }
    
    /**
     * Abre o Editor E4J i*
     */
    private void showE4JiStar() throws HeadlessException, IOException {      
         if (E4JiStar == null) {
            E4JiStar = new EditorJFrame(0);
            E4JiStar.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            E4JiStar.setIconImage(iconJGOOSE);
            E4JiStar.setExtendedState(MAXIMIZED_BOTH);
            EditorWindowListener windowListener = new EditorWindowListener(this, E4JiStar);
            this.addWindowListener(windowListener);
            E4JiStar.addWindowListener(windowListener);
            this.addWindowListener(windowListener);
            BasicIStarEditor editor = (BasicIStarEditor) E4JiStar.getEditor();
            JMenuBar menubar = E4JiStar.getJMenuBar();
            // get diagram menu ba
            JMenu fileMenu = ((EditorMenuBar) menubar).getFileMenu();
            // alias label = l
            String label = mxResources.get("useCaseMaker", null, "Generate Use Cases");
            JMenuItem menuItem = new JMenuItem(editor.bind(label, new ImportIStarGraph(E4JiStar)));
            fileMenu.add(menuItem, 3);
            fileMenu.add(new JPopupMenu.Separator(), 4);
            String label1 = mxResources.get("traceabilityMaker", null, "Horizontal Traceability");
            JMenuItem menuItem1 = new JMenuItem(editor.bind(label1, new HorizontalIStarTraceController(E4JiStar)));
            fileMenu.add(menuItem1, 3);
            fileMenu.add(new JPopupMenu.Separator(), 4);
            String label2 = mxResources.get("traceabilityMaker", null, "Vertical Traceability");
            JMenuItem menuItem2 = new JMenuItem(editor.bind(label2, new VerticalTraceController(2)));
            fileMenu.add(menuItem2, 3);
            fileMenu.add(new JPopupMenu.Separator(), 4);
            
            /*String label2 = mxResources.get("traceabilityMaker", null, "Vertical Traceability");
            JMenuItem menuItem2 = new JMenuItem(editor.bind(label2, new HorizontalIStarTraceController(E4JiStar)));
            fileMenu.add(menuItem2, 3);
            fileMenu.add(new JPopupMenu.Separator(), 4);*/
            

            //diagramMenu.addSeparator();
            //label = mxResources.get("iStarMLMaker", null, "Gerar iarML");
            // menu.add(editor.bind(label, new GenerateIStarMLAction()));
            //menubar.add(diagramMenu);
        }
        Controller.setMainView(this);
        E4JiStar.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Abre o Editor E4J Use Cases
     */
    private void showE4JUseCases() throws HeadlessException, IOException {
        if (E4JUseCases == null) {
            E4JUseCases = new EditorJFrame(1);
            E4JUseCases.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            E4JUseCases.setIconImage(iconJGOOSE);
            E4JUseCases.setExtendedState(MAXIMIZED_BOTH);
            EditorWindowListener windowListener = new EditorWindowListener(this, E4JUseCases);
            this.addWindowListener(windowListener);
            E4JUseCases.addWindowListener(windowListener);
            this.addWindowListener(windowListener);
            BasicUseCasesEditor editor = (BasicUseCasesEditor) E4JUseCases.getEditor();
            JMenuBar menubar = E4JUseCases.getJMenuBar();
            JMenu fileMenu = ((EditorMenuBar) menubar).getFileMenu();
            String label1 = mxResources.get("traceabilityMaker", null, "Horizontal Traceability");
            JMenuItem menuItem1 = new JMenuItem(editor.bind(label1, new HorizontalUseCaseTraceController(E4JUseCases)));
            fileMenu.add(menuItem1, 3);
        }
        Controller.setMainView(this);
        E4JUseCases.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Abre o Editor E4J BPMN
     */
    private void showE4JBPMN() throws HeadlessException, IOException {
        try{
            
            if (E4JBPMN == null) {            
                E4JBPMN = new EditorJFrame(2);
                E4JBPMN.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                EditorWindowListener windowListener = new EditorWindowListener(this, E4JBPMN);
                E4JBPMN.setIconImage(iconJGOOSE);
                E4JBPMN.setExtendedState(MAXIMIZED_BOTH);
                this.addWindowListener(windowListener);
                E4JBPMN.addWindowListener(windowListener);
                this.addWindowListener(windowListener);
                editor = (BasicBPMNEditor) E4JBPMN.getEditor();

                // get diagram menu bar and shows option to derive Use Cases
                JMenuBar menubar = E4JBPMN.getJMenuBar();
                JMenu fileMenu = ((EditorMenuBar) menubar).getFileMenu();
                String label1 = mxResources.get("traceabilityMaker", null, "Horizontal Traceability");
                JMenuItem menuItem1 = new JMenuItem(editor.bind(label1, new HorizontalBPMNTraceController(E4JBPMN)));
                fileMenu.add(menuItem1, 3);
                fileMenu.add(new JPopupMenu.Separator(), 4);
                String label2 = mxResources.get("traceabilityMaker", null, "Vertical Traceability");
                JMenuItem menuItem2 = new JMenuItem(editor.bind(label2, new VerticalTraceController(1)));
                fileMenu.add(menuItem2, 3);
                fileMenu.add(new JPopupMenu.Separator(), 4);
                String label = mxResources.get("useCaseMaker", null, "Generate Use Cases");
                JMenuItem menuItem = new JMenuItem(editor.bind(label, new ImportBPMNGraph(E4JBPMN)));
                fileMenu.add(menuItem, 3);
                fileMenu.add(new JPopupMenu.Separator(), 4);

            }               
            BPMNController.setMainView(this);
            E4JBPMN.setVisible(true);
            this.setVisible(false);
        } catch(Exception e){
            StringBuilder sb = new StringBuilder(e.toString());
            for (StackTraceElement ste : e.getStackTrace()) {
                sb.append("\n\tat ");
                sb.append(ste);
            }
            String trace = sb.toString();
            JOptionPane.showMessageDialog(null, trace);
        }
    }
    
    /**
     * Abre a janela de Rastreabilidade
     */
    private void showTraceability() {
        try{
            if (E4JTraceability == null) {            
                E4JTraceability = new EditorJFrame(3);
                E4JTraceability.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                EditorWindowListener windowListener = new EditorWindowListener(this, E4JTraceability);
                E4JTraceability.setIconImage(iconJGOOSE);
                E4JTraceability.setExtendedState(MAXIMIZED_BOTH);
                /*
                this.addWindowListener(windowListener);
                E4JBPMN.addWindowListener(windowListener);
                this.addWindowListener(windowListener);
                editor = (BasicBPMNEditor) E4JBPMN.getEditor();

                // get diagram menu bar and shows option to derive Use Cases
                JMenuBar menubar = E4JBPMN.getJMenuBar();
                JMenu fileMenu = ((EditorMenuBar) menubar).getFileMenu();
                String label = mxResources.get("useCaseMaker", null, "Generate Use Cases");
                JMenuItem menuItem = new JMenuItem(editor.bind(label, new ImportBPMNGraph(E4JBPMN)));
                fileMenu.add(menuItem, 3);
                fileMenu.add(new JPopupMenu.Separator(), 4);*/
            } 
          //  HorizontalBPMNTraceController.setMainView(this);
            E4JTraceability.setVisible(true);
            this.setVisible(false);
           // TraceabilityView obj = new TraceabilityView();
           // obj.setVisible(true);   
        }catch(Exception e){
            
        }
        
    }
    
    /**
     * Abre a janela de tabelas
    */
    private void showArtfactTables (){
        try{
            if (tableArtifacts == null) {            
                tableArtifacts = new TableArtifacts();
                tableArtifacts.setIconImage(iconJGOOSE);
                tableArtifacts.setExtendedState(MAXIMIZED_BOTH);
                tableArtifacts.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                EditorWindowListener windowListener = new EditorWindowListener(this, tableArtifacts);
                this.addWindowListener(windowListener);
                tableArtifacts.addWindowListener(windowListener);
                this.addWindowListener(windowListener);

            }
            tableArtifacts.setVisible(true); 
            this.setVisible(false);

        }catch(Exception e){
            StringBuilder sb = new StringBuilder(e.toString());
                for (StackTraceElement ste : e.getStackTrace()) {
                    sb.append("\n\tat ");
                    sb.append(ste);
                }
            String trace = sb.toString();
            JOptionPane.showMessageDialog(null, trace);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JButton btnTraceability;
    private javax.swing.JButton buttonBPMNToUseCases;
    private javax.swing.JButton buttonOpenE4JBPMN;
    private javax.swing.JButton buttonOpenE4JUseCases;
    private javax.swing.JButton buttonOpenE4JiStar;
    private javax.swing.JButton buttonOpenTelosFile;
    private javax.swing.JButton buttunMappingUseCases;
    private javax.swing.JMenuItem fileOpenTelosFile;
    private javax.swing.JMenuItem helpAbout;
    private javax.swing.JMenuItem helpGuidelines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenuItem toolsOpenE4JBPMNEditor;
    private javax.swing.JMenuItem toolsOpenE4JEditor;
    private javax.swing.JMenuItem toolsOpenE4JUCEditor;
    // End of variables declaration//GEN-END:variables



}
