package br.unioeste.jgoose.view;

import br.unioeste.jgoose.controller.Controller;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author Diego Peliser
 */
public class SelectActorView extends javax.swing.JFrame {

    private MainView main = new MainView();

    /**
     * Creates new form SelectActorView
     *
     * @param interfacePrincipal
     */
    public SelectActorView() {

        // 0=ok
        JPanel panel = new JPanel();
        panel.setSize(new Dimension(400, 200));
        panel.setLayout(null);
        JLabel label1 = new JLabel("Select the Actor System");
        label1.setVerticalAlignment(SwingConstants.BOTTOM);
        label1.setBounds(45, 10, 200, 10);
        label1.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(label1);
        UIManager.put("OptionPane.minimumSize", new Dimension(350, 150));
        Icon icon =  new ImageIcon("E −\\new.PNG");;
        
        initComponents();
   //     atorSistema.setSize(30, 20);
  //      atorSistema.setBounds(45, 30, 200, 15);
        
       // panel.add(ok);
        for (int i = 0; i < Controller.getOme().getActors().size(); i++) {
            atorSistema.addItem(Controller.getOme().getActor(i).getName());
        }
        panel.add(atorSistema);
        int input = JOptionPane.showConfirmDialog(null, panel, 
                "System Actor", JOptionPane.DEFAULT_OPTION);
        if(input == 0){
            int selecionado = atorSistema.getSelectedIndex();
            for (int i = 0; i < Controller.getOme().getActors().size(); i++) {
                if(i == selecionado){
                    Controller.setSystemActor(Controller.getOme().getActor(i).getCod());
                    break;
                }
            }
            
        } 
    }

    public SelectActorView(MainView interfacePrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        main = interfacePrincipal;
        Image Icone;
        Icone = Toolkit.getDefaultToolkit().getImage("./src/main/resources/icons/jgoose.gif");
        setIconImage(Icone);
        /*
         * Atualiza ComboBox Ator Sistema
         */
        for (int i = 0; i < Controller.getOme().getActors().size(); i++) {
            atorSistema.addItem(Controller.getOme().getActor(i).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        atorSistema = new javax.swing.JComboBox();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("System Actor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select the System Actor:");

        atorSistema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atorSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atorSistemaActionPerformed(evt);
            }
        });

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ok_16x16.png"))); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atorSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ok)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atorSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {atorSistema, ok});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        Controller.setSystemActor(atorSistema.getSelectedIndex());
        dispose();
    }//GEN-LAST:event_okActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        main.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void atorSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atorSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atorSistemaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox atorSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
